/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventanas;

import Validations.Validations;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import redes.Correccion;
import redes.Hamming;

/**
 *
 * @author fabio
 */
public class HammingVentana extends javax.swing.JFrame {

    
    private int instance;
    public final int ENVIO = 1;
    public final int CORRECCION = 0; 
    private File file;
    
    public HammingVentana() {
        instance = ENVIO;
        initComponents();
    }
    
    public void clearall(){
        file = null;
        rutaTF.setText("");
        SalidaTA.setText("");
        entradaTA.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        ruta = new javax.swing.JLabel();
        rutaTF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        seleccB = new javax.swing.JButton();
        envioS = new javax.swing.JRadioButton();
        CorrS = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        entradaTA = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        SalidaTA = new javax.swing.JTextArea();
        AccionB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ruta.setText("Ruta del archivo");

        rutaTF.setEditable(false);

        jLabel1.setText("Hamming");

        seleccB.setText("Seleccionar");
        seleccB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccBActionPerformed(evt);
            }
        });

        envioS.setSelected(true);
        envioS.setText("Envio");
        envioS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                envioSActionPerformed(evt);
            }
        });

        CorrS.setText("Corrección");
        CorrS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorrSActionPerformed(evt);
            }
        });

        entradaTA.setEditable(false);
        entradaTA.setColumns(20);
        entradaTA.setRows(5);
        jScrollPane1.setViewportView(entradaTA);

        SalidaTA.setEditable(false);
        SalidaTA.setColumns(20);
        SalidaTA.setRows(5);
        jScrollPane2.setViewportView(SalidaTA);

        AccionB.setText("Generar");
        AccionB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccionBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ruta)
                        .addGap(48, 48, 48)
                        .addComponent(rutaTF, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(seleccB))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(102, 102, 102)
                            .addComponent(envioS)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CorrS))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(284, 284, 284)
                            .addComponent(jLabel1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(AccionB)))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(envioS)
                    .addComponent(CorrS))
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruta)
                    .addComponent(rutaTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seleccB))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(46, 46, 46)
                .addComponent(AccionB)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seleccBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccBActionPerformed
        JFileChooser fc = new JFileChooser();
        if(instance == ENVIO){
            fc.setFileFilter(new FileNameExtensionFilter("Text files", "txt"));
        }
        else{
            fc.setFileFilter(new FileNameExtensionFilter("ham files", "ham"));
        }
        int res = fc.showOpenDialog(this);
        if(res == JFileChooser.APPROVE_OPTION){
            File f = fc.getSelectedFile();
            switch(instance){
                
                case ENVIO:
                if(Validations.ValidFileEnvio(f,2)){
                    try {
                        file = f;
                        Scanner scan = new Scanner(f);
                        
                        String linea = scan.nextLine();
                        entradaTA.setText(linea);
                        rutaTF.setText(f.getAbsolutePath());


                    } catch (FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(null,"El archivo Tiene problemas","Error",
                        JOptionPane.ERROR_MESSAGE);
                    }
                }
                break;
                
                case CORRECCION:
                    if(Validations.ValidFileHamm(f,12)){
                    try {
                        file = f;
                        Scanner scan = new Scanner(f);
                        while(scan.hasNext()){
                            String linea = scan.nextLine();
                            entradaTA.append(linea+"\n");
                            rutaTF.setText(f.getAbsolutePath());
                        }

                    } catch (FileNotFoundException ex) {
                        JOptionPane.showMessageDialog(null,"El archivo Tiene problemas","Error",
                        JOptionPane.ERROR_MESSAGE);
                    }
                }
                break;
        
            }
        }
    }//GEN-LAST:event_seleccBActionPerformed

    private void AccionBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccionBActionPerformed
        try {
            Scanner scan = new Scanner(file);
            if(file != null){
                if(instance == ENVIO){
                    
                    String linea = scan.nextLine();
                    Hamming hamm = new Hamming(linea);
                    String n = file.getCanonicalPath().substring(0, file.getCanonicalPath().length()-4);
                    File out = hamm.createMessageFile(n);
                    JOptionPane.showMessageDialog(this, "El archivo fue creado exitosamente en "
                            + out.getAbsolutePath());
                    scan = new Scanner(out);
                    while(scan.hasNext()){
                        linea = scan.nextLine();
                        SalidaTA.append(linea+"\n");
                        
                        
                    }
                }
                else{
                    Scanner scanf = new Scanner(file);
                    while(scanf.hasNext()){
                        String line = scanf.nextLine();
                        Correccion cr = new Correccion(line);
                        String k = cr.verifyErrors();
                        SalidaTA.append(k);
                        
                    }
                }
            }
            else{
                 JOptionPane.showMessageDialog(null, "No ha cargado un archivo valido", "Error",
                    JOptionPane.ERROR_MESSAGE);
            }
            
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(null, "El archivo Tiene problemas", "Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "El archivo Tiene problemas", "Error",
                    JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_AccionBActionPerformed

    private void envioSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_envioSActionPerformed
        if(envioS.isSelected()){
            instance = ENVIO;
            AccionB.setText("Generar");
            CorrS.setSelected(false);
            clearall();
           
        }
        //System.out.println(instance);
    }//GEN-LAST:event_envioSActionPerformed

    private void CorrSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CorrSActionPerformed
        if(CorrS.isSelected()){
            instance = CORRECCION;
            AccionB.setText("CORRECCION");
            envioS.setSelected(false);
            clearall();
        }
        //System.out.println(instance);
    }//GEN-LAST:event_CorrSActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HammingVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HammingVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HammingVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HammingVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HammingVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccionB;
    private javax.swing.JRadioButton CorrS;
    private javax.swing.JTextArea SalidaTA;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea entradaTA;
    private javax.swing.JRadioButton envioS;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel ruta;
    private javax.swing.JTextField rutaTF;
    private javax.swing.JButton seleccB;
    // End of variables declaration//GEN-END:variables
}
